#!/bin/sh /etc/rc.common

# Consumed by OpenWrt's rc.common framework.
# shellcheck disable=SC2034
START=95
# shellcheck disable=SC2034
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/fm350-autoconfig --wait 120
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
